---
# Items that apply to ALL profiles:
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: 8030
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: microspring8-sentence-server-hystrix-lab7,subject,verb,article,adjective,noun
  

management:
  port: 8990  
